version: 0.2

env:
  variables:
    DRY_RUN: 'true'
  secrets-manager:
    GITHUB_TOKEN: codebuild/mwaa:GITHUB_TOKEN

phases:
  build:
    commands:
      - |
        if [ "$CODEBUILD_WEBHOOK_TRIGGER" = "branch/main" ]; then
          DRY_RUN=false
        fi

        if [ "$DRY_RUN" = "true" ]; then
          echo "Running dry-run mode"
          ./scripts/airflow/dryrun.sh
        else
          echo "Running deploy"
          ./scripts/airflow/sync.sh
        fi
